romanzipp/Laravel-Twitch

- src/Traits/ExtentionsTrait.php
- src/Twitch.php
- twitch-api.php
I've added functions to get the extensions for the currently authed user.
These two functions have been added:
1) getAuthedUserExtensions(): this functions returns all extensions. 
2) getAuthedUserActiveExtensions(): this function returns only the active extensions.
Please note that you need the scope "user:edit:broadcast" or "user:read:broadcast" to use these.
> add the Extensions Endpoint

- README.md
Changed "Extensions" to "Clips".
> Fix wrong Title in Readme

- src/Traits/ExtensionsTrait.php
> Fix method documentation for extensions trait

- .github/workflows/tests.yml
- README.md
- README.stub
- README.stub.md
- generator/generate-docs.php
- src/Enums/GrantType.php
- src/Exceptions/RequestRequiresClientSecretException.php
- src/Traits/OAuthTrait.php
- src/Twitch.php
- tests/Api/OAuthTest.php
- tests/ServiceGettersTest.php
- tests/TestCases/ApiTestCase.php
```diff
- public function getOAuthToken(string $code): Result
+ public function getOAuthToken(?string $code = null, string $grantType = GrantType::AUTHORIZATION_CODE, array $scopes = []): Result
```
No backwards compatibility issues.
https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-client-credentials-flow
```php
$twitch = new romanzipp\Twitch;
$twitch->getOAuthToken(
null,
romanzipp\Twitch\Enums\GrantType::CLIENT_CREDENTIALS,
[ 'user:read' ]
);
```
> OAuth Updates

- src/Concerns/Api/BitsTrait.php
- src/Concerns/Api/ClipsTrait.php
- src/Concerns/Api/ExtensionsTrait.php
- src/Concerns/Api/FollowsTrait.php
- src/Concerns/Api/GamesTrait.php
- src/Concerns/Api/ModerationTrait.php
- src/Concerns/Api/OAuthTrait.php
- src/Concerns/Api/StreamsMetadataTrait.php
- src/Concerns/Api/StreamsTrait.php
- src/Concerns/Api/SubscriptionsTrait.php
- src/Concerns/Api/UsersTrait.php
- src/Concerns/Api/VideosTrait.php
- src/Concerns/Api/WebhooksTrait.php
- src/Concerns/Operations/GetTrait.php
- src/Concerns/Operations/JsonTrait.php
- src/Concerns/Operations/PostTrait.php
- src/Concerns/Operations/PutTrait.php
- src/Twitch.php
For a long time I had the idea to outsource the API operations as separate trais. I've finally put that into effect. What do you think of it? This has the advantage that typos can be eliminated.
> Cleanup API Operations

- README.md
- README.stub.md
- config/twitch-api.php
- generator/generate-docs.php
- src/Concerns/Api/EventSubTrait.php
- src/Enums/EventSubType.php
- src/Events/EventSubHandled.php
- src/Events/EventSubReceived.php
- src/Exceptions/SignatureVerificationException.php
- src/Http/Controllers/EventSubController.php
- src/Http/Middleware/VerifyEventSubSignature.php
- src/Objects/EventSubNotification.php
- src/Objects/EventSubSignature.php
- src/Twitch.php
- tests/Api/EventSubTest.php
- tests/EventSubControllerTest.php
- tests/VerifyEventSubSignatureTest.php
I added the new event sub implementation.
I have also implemented an [event handler](https://github.com/ghostzero/Laravel-Twitch/tree/webhooks-2.0#defining-websub-event-handlers) to simplify the handling of EventSub (including Secret + Signature check). So you only have to extend the `EventSubController` and register your controller in the routes.
Feel free to share your feedback 😃
> WIP: EventSub

- composer.json
this will allow us to use this package in projects that use updated versions of PHP 8
> Allow for updated PHP 8 verisons

- src/Concerns/Api/SubscriptionsTrait.php
Adding the endpoint to check if a specific user is subscribed to a specific channel.
> Add Check User Subscription

- src/Concerns/Api/ChannelPoints.php
- src/Twitch.php
> Add new endpoints

- README.md
- README.stub.md
- config/twitch-api.php
- src/Concerns/Api/EventSubTrait.php
- src/Enums/EventSubType.php
- src/Http/Controllers/EventSubController.php
- src/Http/Middleware/VerifyEventSubSignature.php
- src/Objects/EventSubSignature.php
- tests/VerifyEventSubSignatureTest.php
Hey, I have revised the documentation a bit, so that everyone can understand how to use the EventSub.
Also I fixed a type. There had been a typo in it. It should be `channel.follow` instead of `user.follow`.
> Update EventSub Documentation and fix non-existent type

- src/Concerns/Api/StreamsTrait.php
- src/Enums/Scope.php
> Add get followed streams

- config/twitch-api.php
- src/Objects/EventSubSignature.php
- tests/VerifyEventSubSignatureTest.php
> Fix default tolerance value & Update config

- src/Concerns/Api/TagsTrait.php
> Fix get all stream tags endpoint

- src/Concerns/Api/ClipsTrait.php
added pagination object support for clips
https://dev.twitch.tv/docs/api/reference#get-clips
> Clip pagination

- README.md
- src/Concerns/Api/WebhooksTrait.php
> Deprecate webhooks

- README.md
- src/Concerns/Api/AdsTrait.php
- src/Concerns/Api/ChatTrait.php
- src/Concerns/Api/ExtensionsTrait.php
- src/Concerns/Api/ModerationTrait.php
- src/Concerns/Api/MusicTrait.php
- src/Concerns/Api/RaidsTrait.php
- src/Concerns/Api/TeamsTrait.php
- src/Concerns/Api/UsersTrait.php
- src/Concerns/Api/VideosTrait.php
- src/Concerns/Api/WhispersTrait.php
- src/Enums/ChatAnnouncementColor.php
- src/Enums/ChatColor.php
- src/Twitch.php
added all missing music, extension, music, teams, users and videos endpoints to the update-endpoints branch
I have also added the newer endpoints (block user, unblock user, whisper, chat announcement, get/update chat color etc.)
> added missing endpoints

- README.md
- src/Concerns/Api/AdsTrait.php
- src/Concerns/Api/ChannelPointsTrait.php
- src/Concerns/Api/ChannelTrait.php
- src/Concerns/Api/ChannelsTrait.php
- src/Concerns/Api/CharityTrait.php
- src/Concerns/Api/ChatTrait.php
- src/Concerns/Api/EntitlementsTrait.php
- src/Concerns/Api/ExtensionsTrait.php
- src/Concerns/Api/GoalsTrait.php
- src/Concerns/Api/ModerationTrait.php
- src/Concerns/Api/MusicTrait.php
- src/Concerns/Api/RaidsTrait.php
- src/Concerns/Api/ScheduleTrait.php
- src/Concerns/Api/StreamsTrait.php
- src/Concerns/Api/TeamsTrait.php
- src/Concerns/Api/UsersTrait.php
- src/Concerns/Api/VideosTrait.php
- src/Concerns/Api/WhispersTrait.php
- src/Concerns/ClientCredentialsTrait.php
- src/Enums/ChatAnnouncementColor.php
- src/Enums/ChatColor.php
- src/Http/Controllers/EventSubController.php
- src/Twitch.php
> Add endpoints

- README.md
- src/Concerns/Api/ChatTrait.php
added new (beta) endpoint chat/chatters: https://dev.twitch.tv/docs/api/reference#get-chatters
> added get chatters endpoint

- README.md
- src/Concerns/Api/ChannelsTrait.php
- src/Concerns/Api/ChatTrait.php
- src/Concerns/Api/ModerationTrait.php
- src/Concerns/Api/UsersTrait.php
Added new endpoints:
- Get Channel Followers
- Get Channels Followed
- Send a Shoutout
- Get Shield Mode Status
- Update Shield Mode Status
and deprecated tag for getUsersFollows
> added new endpoints, deprecated notice old followers endpoint

- src/Concerns/Api/OAuthTrait.php
- src/Result.php
> Add validate oauth token endpoint

- src/Concerns/Api/OAuthTrait.php
> Fix GET validate endpoint method
